= Apache Kafka Images

Docker image for running the link:https://github.com/apache/kafka/[Open Source version of Apache Kafka]. It offers support for running Kafka in link:https://github.com/apache/kafka/blob/3.0.0/config/kraft/README.md[KRaft] mode as well as in ZooKeeper mode.

The Kafka distribution included in the Docker image is built directly from link:https://github.com/apache/kafka/[source].

The Docker images are available on the following DockerHub repositories:

* link:https://hub.docker.com/repository/docker/ueisele/apache-kafka-server[ueisele/apache-kafka-server]
* link:https://hub.docker.com/repository/docker/ueisele/apache-kafka-server-standalone[ueisele/apache-kafka-server-standalone]

== Quick Start

.To start Kafka in KRaft single mode just run: 
[source,bash]
----
docker run --rm -p 9092:9092 ueisele/apache-kafka-server-standalone:3.0.0
----

.To start Kafka in KRaft single mode with Ipv6 just run: 
[source,bash]
----
docker network create --ipv6 --subnet fd01::/80 kafka-standalone
docker run --rm -p 9092:9092 --net kafka-standalone -e STANDALONE_BROKER_IP_VERSION=ipv6 ueisele/apache-kafka-server-standalone:3.0.0
----

== Docker Compose Examples

.To start Kafka in KRaft single mode just run: 
[source,bash]
----
cd example/kraft-single-mode
docker-compose up
----

You find all examples in link:examples/kraft/[]:

* link:examples/kraft/single-mode/docker-compose.yaml[]
* link:examples/kraft/cluster-shared-mode/docker-compose.yaml[]
* link:examples/kraft/cluster-dedicated-mode/docker-compose.yaml[]
* link:examples/kraft/cluster-mixed-mode/docker-compose.yaml[]
* link:examples/kraft/cluster-ssl-pem/docker-compose.yaml[]
* link:examples/kraft/cluster-ssl-jks/docker-compose.yaml[]
* link:examples/kraft/cluster-ssl-pkcs12/docker-compose.yaml[]

== Build and Configuration

* OpenJDK base image: link:openjdk/[]
* Apache Kafka server image: link:server/[]
* Apache Kafka server standalone image: link:server-standalone/[]

== KRaft Mode

Kafka 2.8 is the first release wich contains KRaft as an operation mode which requires no ZooKeeper.
KRaft mode in Kafka 2.8 and 3.0 is provided for testing only, NOT for production. 
It is not yet supported to upgrade existing ZooKeeper-based Kafka clusters into this mode. 
In fact, when Kafka 3.1 is released, it will not be possible to upgrade your KRaft clusters from 3.0 to 3.1. 
There may be bugs, including serious ones. You should assume that your data could be lost at any time if you try the early access release of KRaft mode.

You find mor information on this sites:

* https://github.com/apache/kafka/blob/3.0.0/config/kraft/README.md
* https://www.confluent.io/blog/kafka-without-zookeeper-a-sneak-peek/