= Apache Kafka Images

Docker image for running the link:https://github.com/apache/kafka/[Open Source version of Apache Kafka]. It offers support for running Kafka in link:https://github.com/apache/kafka/blob/3.1.0/config/kraft/README.md[KRaft] mode as well as in ZooKeeper mode.

The Kafka distribution included in the Docker image is built directly from link:https://github.com/apache/kafka/[source].

The Docker images are available on the following DockerHub repositories:

* link:https://hub.docker.com/repository/docker/ueisele/apache-kafka-server[ueisele/apache-kafka-server]
* link:https://hub.docker.com/repository/docker/ueisele/apache-kafka-server-standalone[ueisele/apache-kafka-server-standalone]
* link:https://hub.docker.com/repository/docker/ueisele/apache-kafka-connect-base[ueisele/apache-kafka-connect-base]
* link:https://hub.docker.com/repository/docker/ueisele/apache-kafka-connect[ueisele/apache-kafka-connect]
* link:https://hub.docker.com/repository/docker/ueisele/apache-kafka-connect-standalone[ueisele/apache-kafka-connect-standalone]

== Quick Start

.To start Kafka in KRaft single mode just run: 
[source,bash]
----
docker run --rm -p 9092:9092 ueisele/apache-kafka-server-standalone:3.1.0
----

.To start Kafka in KRaft single mode with Ipv6 just run: 
[source,bash]
----
docker network create --ipv6 --subnet fd01::/80 kafka-standalone
docker run --rm -p 9092:9092 --net kafka-standalone -e STANDALONE_BROKER_IP_VERSION=ipv6 ueisele/apache-kafka-server-standalone:3.1.0
----

== Docker Compose Examples

In this section you find an overview about the Kafka Server and Kafka Connect examples.

=== Kafka KRaft Mode Examples

.To start Kafka in KRaft single mode just run: 
[source,bash]
----
cd example/kraft/single-mode
docker-compose up
----

You find all examples in link:examples/kraft/[]:

* link:examples/kraft/single-mode/docker-compose.yaml[]
* link:examples/kraft/cluster-shared-mode/docker-compose.yaml[]
* link:examples/kraft/cluster-dedicated-mode/docker-compose.yaml[]
* link:examples/kraft/cluster-mixed-mode/docker-compose.yaml[]
* link:examples/kraft/cluster-ssl-pem/docker-compose.yaml[]
* link:examples/kraft/cluster-ssl-jks/docker-compose.yaml[]
* link:examples/kraft/cluster-ssl-pkcs12/docker-compose.yaml[]

=== Kafka ZooKeeper Mode Examples

.To start Kafka in ZooKeeper mode just run: 
[source,bash]
----
cd example/zk/cluster
docker-compose up
----

You find additional examples in link:examples/zk/[]:

* link:examples/zk/cluster/docker-compose.yaml[]

=== Connect Examples

.To start Kafka Connect in standalone mode just run: 
[source,bash]
----
cd example/connect-standalone/file-source
docker-compose up
----

You find additional examples in link:examples/connect-standalone/[]:

* link:examples/connect-standalone/file-source/docker-compose.yaml[]
* link:examples/connect-standalone/datagen-plugin-install/docker-compose.yaml[]
* link:examples/connect-standalone/http-source-plugin-install/docker-compose.yaml[]

== Build and Configuration

* OpenJDK base image: link:openjdk/[]
* Apache Kafka server image: link:server/[]
* Apache Kafka server standalone image: link:server-standalone/[]
* Apache Kafka Connect base image: link:connect-base/[]
* Apache Kafka Connect image: link:connect/[]
* Apache Kafka Connect standalone image: link:connect-standalone/[]

== Podman and Podman Compose Support

The examples can also be used with link:https://github.com/containers/podman-compose[podman-compose].

[source,bash]
----
cd example/kraft/single-mode
podman-compose up
----

It is important to note that at least link:https://github.com/containers/podman-compose[podman-compose] 1.0.4 is required. The reason is, that in the examples network alias are used. Unfortunately, 1.0.4 is not released at the moment. However, you could install it manually.


[source,bash]
----
pip3 install --upgrade --target=${HOME}/Applications/podman-compose git+https://github.com/containers/podman-compose.git
cat > ~/.local/bin/podman-compose <<EOF
PODMAN_COMPOSE_PATH=${HOME}/Applications/podman-compose
PYTHONPATH=\${PODMAN_COMPOSE_PATH} \${PODMAN_COMPOSE_PATH}/bin/podman-compose \$@
EOF
chmod +x ~/.local/bin/podman-compose
----
