#!/usr/bin/env bash
set -e
EXAMPLE_DIR="$(readlink -f "$(dirname ${BASH_SOURCE[0]})")"

source "${EXAMPLE_DIR}/.env"
source "${EXAMPLE_DIR}/generate-ca"
source "${EXAMPLE_DIR}/generate-cert"
source "${EXAMPLE_DIR}/btpl"

export TARGET_DIR="${EXAMPLE_DIR}/target"
export GROUP=kafka-broker
export CA_KEY_PASS="cakeypass"
export CA_TRUSTSTORE_PASS="changeit"
export CERT_KEY_PASS="certkeypass"
export KEYSTORE_PASS="changeit"
generateCA
NAME=server CERT_SAN="IP:127.0.0.1,DNS:localhost,DNS:kafka,DNS:kafka-broker1,DNS:kafka-broker2,DNS:kafka-broker3" generateCert

btpl "${EXAMPLE_DIR}/client.properties.btpl" "${TARGET_DIR}/client.properties"

if command -v podman &> /dev/null; then
  # if podman is installed, set permissions of generated artifacts to allow access by user appuser if podman is used in rootless mode
  chmod -R ugo=rwX ${TARGET_DIR}
  podman unshare chown -R 1000:1000 ${TARGET_DIR}
fi
