#!/usr/bin/env bash
#
# Copyright 2016 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. /opt/apache/kafka/docker/bash-config

# Set environment values if they exist as arguments
if [ $# -ne 0 ]; then
  echo "===> Overriding env params with args ..."
  for var in "$@"
  do
    export "$var"
  done
fi

echo "===> OS"
cat /etc/os-release

echo "===> Java"
java -version

echo "===> User"
id

echo "===> Configuring ..."
/opt/apache/kafka/docker/configure

echo "===> Initializing ..."
/opt/apache/kafka/docker/init

echo "===> Running preflight checks ... "
/opt/apache/kafka/docker/ensure

echo "===> Launching ... "
exec /opt/apache/kafka/docker/launch
