name: Apache Kafka Server Snapshot Build and Push

on:
  schedule:
  - cron:  '0 4 * * 3,6'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        run: ./build-all.sh --modules server --modes build,push --versions snapshot