name: Kcat Snapshot Build and Push

on:
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        kcat: ["master"]
        librdkafka: ["2.0.2"]
      fail-fast: false
    
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        run: ./kcat/build.sh --build --branch ${{ matrix.kcat }} --librdkafka-version ${{ matrix.librdkafka }}
      -
        name: Push
        run: ./kcat/build.sh --push --branch ${{ matrix.kcat }} --librdkafka-version ${{ matrix.librdkafka }}
