name: Kcat Release Build and Push

on:
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        kcat: ["1.7.1"]
        librdkafka: ["2.0.2", "2.1.1"]
      fail-fast: false
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build
      run: ./kcat/build.sh --build --tag ${{ matrix.kcat }} --librdkafka-version ${{ matrix.librdkafka }}
    - name: Push
      run: ./kcat/build.sh --push --tag ${{ matrix.kcat }} --librdkafka-version ${{ matrix.librdkafka }}
