name: OpenJDK Build and Push

on:
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        release: ["8", "11", "17", "19"]
      fail-fast: false
    
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        run: ./openjdk/build.sh --build --openjdk-release ${{ matrix.release }}
      -
        name: Push
        run: ./openjdk/build.sh --push --openjdk-release ${{ matrix.release }}
